### ISSUE TITLE
Change initial value for props

### ISSUE THREAD

**Issue by ChristopherParo** [stutrek/scrollmonitor-react#21]
Wanting to try to have the initial value, specifically in my case the isInViewport prop, to be true on the initial load. Is there a way to do this?

I've tried avoiding the initial false value by turning off autoStart but it seems to still pass a false value first than it stops the watch.

I've also tried to set the default prop to be true but it overrides the default to false than back to true.

**Comment by stutrek** [comment]
Because of the way React works those values can't be guaranteed correct on initial load.

If you have the time or energy to put into a PR, having the HOC pass in an `initialRender` prop could be an easy workaround, or giving the component a prop called `initalScrollMonitorState` or something similar could be handy.

**Comment by ChristopherParo** [comment]
Added a pull request to add the InitialRender prop which will allow you to pass an object to set initial state in the HOC #22
